- docs/lectures/nlp_intro.md
- docs/lectures/nlp_pipeline.md
> Image paths relative to parent directory

- docs/assignments.md
Describing ways for students to use git to work on the assignments in their local repositories.
closes #41
> Add git guide for assignments

- docs/presentations/articles/template.md
- docs/presentations/presentations.md
- mkdocs.yml
> Add article submission info

- .pre-commit-config.yaml
- tests/htwgnlp/test_features.py
- tests/htwgnlp/test_logistic_regression.py
> Add isort as pre-commit hook

- src/htwgnlp/features.py
The description of what `pos` and `neg` should express was misleading and I hope that makes it clearer now.
Thanks for the hint @ka161heg 🚀
> Update docstring for get features

- Makefile
- docs/getting_started.md
> Updates on project setup

- docs/about/course_profile.md
- docs/about/prerequisites.md
> Revisit About page

- CONTRIBUTING.md
- Makefile
- pyproject.toml
> Improve development setup

- .pre-commit-config.yaml
- Makefile
- pyproject.toml
> Add ruff linter

- .markdownlint.json
- .pre-commit-config.yaml
- Makefile
- README.md
- docs/index.md
- docs/lectures/introduction.md
- includes/abbreviations.md
- mkdocs.yml
> Add Markdown linter

- src/htwgnlp/python_basics.py
- tests/htwgnlp/files/test_data.json
- tests/htwgnlp/test_python_basics.py
> Add assignment for Python basics

- docs/faq.md
This question came up in the lecture and I added it to the FAQs
> Add question about sample solutions

- CONTRIBUTING.md
- README.md
- docs/assignments.md
- docs/course_profile.md
- docs/faq.md
- docs/index.md
- docs/presentations.md
This changes the assignment policy of the course:
- assignments are now voluntary
- assignments are eligible for bonus points
- a total of 10 bonus points can be earned during the semester
> Change assignment policy

- docs/faq.md
I received questions on whether it is mandatory to attend the lectures. It is not, and I added that information to the FAQs.
> Add FAQ that lectures are not mandatory

- docs/presentations.md
Otherwise, we will run short on time.
> Limit presentation scope to 10 minutes

- docs/lectures/logistic_regression.md
- docs/lectures/naive_bayes.md
Minor updates after session 4 on logistic regression and naive bayes lecture.
> Session 4 lecture updates

- notebooks/minimum_edit_distance.ipynb
Update the notebook to include instructions for the fifth assignment, including the requirement for screenshots of outputs and specific TODO comments for implementation.
You can search for `TODO ASSIGNMENT-5` in the code.
> Notebook for minimum edit distance is now assignment 5

- Makefile
- docs/assignments.md
- docs/getting_started.md
- pyproject.toml
Updated/replaced jupyter dependency to use jupyterlab.
> New jupyterlab dependency

- docs/lectures/word_embeddings.md
Minor updates before the lecture
> Update word embeddings lecture

- docs/exam.md
- mkdocs.yml
- Adds basic information about exam
- Adding a grade scale
> Add information about exam

- src/htwgnlp/embeddings.py
> embeddings.py: specified typehint for metric parameter

- tests/htwgnlp/test_embeddings.py
> extended find_closest_word unittest to cover both similarity metrics

- src/htwgnlp/embeddings.py
- tests/htwgnlp/test_embeddings.py
> precommit check fails without none type check in embeddings assignment
